version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    # A container that exposes an API to show its IP address
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password1234'
    # labels:
    #   - "traefik.http.routers.mysql.rule=Host(`mysql.docker.localhost`)"
  phpmyadmin:
    # A container that exposes an API to show its IP address
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.p82.it`)"
    links:
    - mysql:db
  wordpress:
    # A container that exposes an API to show its IP address
    image: wordpress
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.p82`)"
    links:
    - mysql:db